#!/usr/bin/env python3
"""Independent Philox4x32-10 reference; emits tests/unit/rng_kat.inl (M0-T4).

04 §2 wants the first 16 uniform_f() of Stream(seed=0, stream=0) frozen as a
project-local known-answer vector. Recording whatever the C++ happens to emit
would prove only that it agrees with itself.

So this is a SECOND implementation, written from the algorithm rather than from
the C++, and it earns the right to emit the golden file only by first
reproducing the three published Random123 vectors — external ground truth that
neither implementation can fake. The C++ then has to match it.

  python rng_kat_gen.py            regenerate tests/unit/rng_kat.inl
  python rng_kat_gen.py --check    exit 1 if the file is stale

Changing the emitted values requires an ADR (04 §2: frozen thereafter).
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "tests" / "unit" / "rng_kat.inl"

M0, M1 = 0xD2511F53, 0xCD9E8D57
W0, W1 = 0x9E3779B9, 0xBB67AE85
ROUNDS = 10
MASK32 = 0xFFFFFFFF
MASK64 = 0xFFFFFFFFFFFFFFFF

# Published Random123 known-answer vectors: (counter, key, expected output).
# Counter/key all-zero; all-ones; and the pi-digit pattern.
RANDOM123_VECTORS = [
    ((0x00000000, 0x00000000, 0x00000000, 0x00000000), (0x00000000, 0x00000000),
     (0x6627E8D5, 0xE169C58D, 0xBC57AC4C, 0x9B00DBD8)),
    ((0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF), (0xFFFFFFFF, 0xFFFFFFFF),
     (0x408F276D, 0x41C83B0E, 0xA20BC7C6, 0x6D5451FD)),
    ((0x243F6A88, 0x85A308D3, 0x13198A2E, 0x03707344), (0xA4093822, 0x299F31D0),
     (0xD16CFE09, 0x94FDCCEB, 0x5001E420, 0x24126EA1)),
]


def philox4x32_10(ctr: tuple[int, int, int, int], key: tuple[int, int]) -> tuple[int, ...]:
    c0, c1, c2, c3 = ctr
    k0, k1 = key
    for r in range(ROUNDS):
        if r > 0:  # key bump happens between rounds, not before round 0
            k0 = (k0 + W0) & MASK32
            k1 = (k1 + W1) & MASK32
        p0 = M0 * c0
        p1 = M1 * c2
        hi0, lo0 = (p0 >> 32) & MASK32, p0 & MASK32
        hi1, lo1 = (p1 >> 32) & MASK32, p1 & MASK32
        c0, c1, c2, c3 = hi1 ^ c1 ^ k0, lo1, hi0 ^ c3 ^ k1, lo0
    return (c0, c1, c2, c3)


class Stream:
    """Mirror of ns::rng::Stream — same layout, written independently."""

    def __init__(self, seed: int, stream: int, ctr: int = 0, sub: int = 0) -> None:
        self.seed, self.stream, self.ctr, self.sub = seed, stream, ctr, sub
        self._refill()

    def _refill(self) -> None:
        self.block = philox4x32_10(
            (self.ctr & MASK32, (self.ctr >> 32) & MASK32,
             self.stream & MASK32, (self.stream >> 32) & MASK32),
            (self.seed & MASK32, (self.seed >> 32) & MASK32),
        )

    def next_u32(self) -> int:
        value = self.block[self.sub]
        self.sub += 1
        if self.sub == 4:
            self.sub = 0
            self.ctr += 1
            self._refill()
        return value

    def uniform_f(self) -> float:
        # float32 round-trip, so the emitted literal is exactly what C++ computes.
        return struct.unpack("f", struct.pack("f", (self.next_u32() >> 8) * 2.0**-24))[0]


def splitmix64(x: int) -> int:
    x = (x + 0x9E3779B97F4A7C15) & MASK64
    x = ((x ^ (x >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
    x = ((x ^ (x >> 27)) * 0x94D049BB133111EB) & MASK64
    return x ^ (x >> 31)


def fork(parent_stream: int, parent_ctr: int, progeny_ordinal: int) -> int:
    rotl = ((parent_ctr << 17) | (parent_ctr >> 47)) & MASK64
    mixed = (0x9E3779B97F4A7C15 * (progeny_ordinal + 1)) & MASK64
    return splitmix64(parent_stream ^ rotl ^ mixed)


def verify_random123() -> None:
    """External ground truth. Nothing is emitted unless all three reproduce."""
    for ctr, key, expected in RANDOM123_VECTORS:
        got = philox4x32_10(ctr, key)
        if got != expected:
            raise SystemExit(
                "rng_kat_gen: FATAL — this reference does not reproduce a published "
                f"Random123 vector, so it cannot certify anything.\n"
                f"  counter={['%08x' % c for c in ctr]} key={['%08x' % k for k in key]}\n"
                f"  expected={['%08x' % e for e in expected]}\n"
                f"  got     ={['%08x' % g for g in got]}"
            )


def render() -> str:
    stream = Stream(seed=0, stream=0)
    values = [stream.uniform_f() for _ in range(16)]
    fork_kat = fork(42, 1000, 3)

    lines = [
        "// GENERATED by tools/verify/rng_kat_gen.py — DO NOT EDIT.",
        "//",
        "// Project-local known-answer vector (04 §2). FROZEN: changing any value here",
        "// changes every random number the project produces and requires an ADR.",
        "//",
        "// Produced by an independent Python Philox that first reproduces the three",
        "// published Random123 vectors, so this file is external evidence about the",
        "// wrapper layout (counter packing, sub-word order, float conversion) rather",
        "// than a recording of what the C++ already did.",
        "",
        "// First 16 uniform_f() of Stream(seed=0, stream=0).",
        "inline constexpr float kRngKatUniformF[16] = {",
    ]
    for i in range(0, 16, 4):
        row = ", ".join(f"{v:.9g}f" for v in values[i:i + 4])
        lines.append(f"    {row},")
    lines += [
        "};",
        "",
        "// fork(42, 1000, 3) — must be identical in ref/ and gpu/ (04 §2c).",
        f"inline constexpr unsigned long long kRngKatFork42_1000_3 = {fork_kat}ull;",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if rng_kat.inl is stale")
    args = parser.parse_args()

    verify_random123()
    text = render()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None

    if args.check:
        if current != text:
            print("rng_kat_gen: STALE — tests/unit/rng_kat.inl does not match the "
                  "independent reference (regenerate, and log an ADR if intentional)",
                  file=sys.stderr)
            return 1
        print("rng_kat_gen: OK — 3 Random123 vectors reproduced; rng_kat.inl current")
        return 0

    if current != text:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"rng_kat_gen: wrote {OUT.relative_to(ROOT).as_posix()}")
    print("rng_kat_gen: OK — 3 published Random123 vectors reproduced")
    return 0


if __name__ == "__main__":
    sys.exit(main())
