#!/usr/bin/env python3
"""Generate data/constants.toml and the C++ constant headers (M0-T3-a).

Input  : spec/appendix/constants.data.toml   (hand-authored, 03 §1)
Outputs: data/constants.toml
         src/core/constants/constants_generated.h
         src/core/constants/constants_generated.cuh

Nothing downstream may hand-edit those outputs — 01 §8 makes this file the
single source of truth for every number in the project.

  python gen_constants.py            regenerate in place
  python gen_constants.py --check    exit 1 if any output is stale

--check is what CI and ctest run: a constant that drifts between the spec and
the code is the failure mode this whole pipeline exists to make impossible.
"""

from __future__ import annotations

import argparse
import math
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STRICT = ROOT / "spec" / "appendix" / "constants.data.toml"

VALID_STATUS = {"PUBLIC", "DECLASSIFIED", "RECONSTRUCTED", "SIM", "PENDING"}
VALID_USE = {"compute", "crosscheck"}

BANNER = (
    "// GENERATED by tools/gen_constants — DO NOT EDIT.\n"
    "// Source of truth: spec/appendix/constants.data.toml (03 §1, 01 §8).\n"
    "// Regenerate with: python tools/gen_constants/gen_constants.py\n"
)


class GenError(Exception):
    """A defect in the strict file. Always fatal — never a warning."""


# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------

def _require(entry: dict, field: str, kind: str) -> object:
    if field not in entry or entry[field] in (None, ""):
        raise GenError(f"{kind} {entry.get('id', '<no id>')}: missing required field '{field}'")
    return entry[field]


def validate(doc: dict) -> None:
    """Reject anything the generator cannot stand behind.

    The DoD requires a hard failure on a missing citation or status: an
    uncited constant in a project whose entire premise is 'public sources
    only' is a provenance defect, not a formatting one.
    """
    if doc.get("schema_version") != 1:
        raise GenError(f"schema_version must be 1, got {doc.get('schema_version')!r}")

    seen: dict[str, str] = {}
    for kind in ("constant", "band", "registry"):
        for entry in doc.get(kind, []):
            cid = str(_require(entry, "id", kind))
            if cid in seen:
                raise GenError(f"duplicate id {cid} (already used by a {seen[cid]})")
            seen[cid] = kind

            _require(entry, "name", kind)
            _require(entry, "cite", kind)
            _require(entry, "appendix_text", kind)
            status = str(_require(entry, "status", kind))
            if status not in VALID_STATUS:
                raise GenError(f"{cid}: status {status!r} not in {sorted(VALID_STATUS)}")

            if kind == "constant":
                _validate_constant(entry, cid, status)
            elif kind == "band":
                _validate_band(entry, cid)
            else:
                _validate_registry(entry, cid)

    if not seen:
        raise GenError("strict file contains no entries")


def _validate_constant(entry: dict, cid: str, status: str) -> None:
    use = str(_require(entry, "use", "constant"))
    if use not in VALID_USE:
        raise GenError(f"{cid}: use {use!r} not in {sorted(VALID_USE)}")

    if status == "PENDING":
        # 03 §1: PENDING may omit value, MUST name the task that resolves it,
        # and MUST raise if read at runtime (the header emits a deleted
        # function so 'read' becomes a compile error).
        _require(entry, "resolved_by", "constant")
        return

    if "value" not in entry and "derived" not in entry:
        raise GenError(f"{cid}: non-PENDING constant needs 'value' or 'derived'")

    lo, hi, value = entry.get("lo"), entry.get("hi"), entry.get("value")
    if (lo is None) != (hi is None):
        raise GenError(f"{cid}: lo and hi must be given together")
    if lo is not None:
        if lo > hi:
            raise GenError(f"{cid}: lo {lo} > hi {hi}")
        if value is not None and not (lo <= value <= hi):
            raise GenError(f"{cid}: value {value} outside band [{lo}, {hi}]")


def _validate_band(entry: dict, cid: str) -> None:
    lo, hi = _require(entry, "lo", "band"), _require(entry, "hi", "band")
    if lo >= hi:
        raise GenError(f"{cid}: band requires lo < hi, got [{lo}, {hi}]")
    if "value" in entry:
        # The whole point of [[band]] (ADR-015) is that a gate band has no
        # physical centre. Allowing a nominal invites someone to compute with it.
        raise GenError(f"{cid}: [[band]] must not carry 'value'")


def _validate_registry(entry: dict, cid: str) -> None:
    entries = entry.get("entries")
    if not isinstance(entries, dict) or not entries:
        raise GenError(f"{cid}: [[registry]] needs a non-empty [registry.entries] table")
    for key, val in entries.items():
        ok = isinstance(val, (int, float)) or (
            isinstance(val, list) and len(val) == 2 and all(isinstance(v, (int, float)) for v in val)
        )
        if not ok:
            raise GenError(f"{cid}.{key}: registry values must be a number or a [lo, hi] pair")


# --------------------------------------------------------------------------
# Derived constants
# --------------------------------------------------------------------------

_ID_TOKEN = re.compile(r"C-\d+[a-z]?")


def resolve_derived(doc: dict) -> dict[str, float]:
    """Evaluate `derived = "..."` expressions by substituting constant ids.

    Restricted to arithmetic over ids already present in the file — no builtins,
    no names. A derived constant that references an unknown id is a hard error.
    """
    by_id = {c["id"]: c for c in doc.get("constant", [])}
    values = {cid: c["value"] for cid, c in by_id.items() if "value" in c}
    computed: dict[str, float] = {}

    for cid, entry in by_id.items():
        expr = entry.get("derived")
        if not expr:
            continue
        refs = _ID_TOKEN.findall(expr)
        missing = [r for r in refs if r not in values]
        if missing:
            raise GenError(f"{cid}: derived expression references unknown id(s) {missing}")
        py = expr
        for ref in sorted(set(refs), key=len, reverse=True):
            py = py.replace(ref, repr(values[ref]))
        if not re.fullmatch(r"[0-9eE_.+\-*/() ]+", py):
            raise GenError(f"{cid}: derived expression is not pure arithmetic: {expr!r}")
        result = eval(py, {"__builtins__": {}}, {})  # noqa: S307 - guarded above

        stated = entry.get("value")
        if stated is not None and not math.isclose(result, stated, rel_tol=1e-4):
            raise GenError(
                f"{cid}: derived value {result:.6e} disagrees with the appendix's "
                f"stated {stated:.6e} by more than 1e-4 relative"
            )
        computed[cid] = result
        entry["value"] = result
    return computed


# --------------------------------------------------------------------------
# Emission
# --------------------------------------------------------------------------

def _num(v: float | int) -> str:
    if isinstance(v, int) and not isinstance(v, bool):
        return str(v)
    return repr(float(v))


def emit_runtime_toml(doc: dict) -> str:
    out = [
        "# GENERATED by tools/gen_constants — DO NOT EDIT.",
        "# Source of truth: spec/appendix/constants.data.toml (03 §1).",
        "",
        "schema_version = 1",
        "",
    ]
    for entry in doc.get("constant", []):
        out.append("[[constant]]")
        out.append(f'id = "{entry["id"]}"')
        out.append(f'name = "{entry["name"]}"')
        if "value" in entry:
            out.append(f"value = {_num(entry['value'])}")
        for opt in ("lo", "hi"):
            if opt in entry:
                out.append(f"{opt} = {_num(entry[opt])}")
        for opt in ("unit", "status", "use", "cite", "resolved_by", "derived", "species"):
            if opt in entry:
                out.append(f'{opt} = "{entry[opt]}"')
        if entry.get("element_averaged"):
            out.append("element_averaged = true")
        out.append("")

    for entry in doc.get("band", []):
        out.append("[[band]]")
        out.append(f'id = "{entry["id"]}"')
        out.append(f'name = "{entry["name"]}"')
        out.append(f"lo = {_num(entry['lo'])}")
        out.append(f"hi = {_num(entry['hi'])}")
        for opt in ("unit", "status", "cite"):
            if opt in entry:
                out.append(f'{opt} = "{entry[opt]}"')
        out.append("")

    for entry in doc.get("registry", []):
        out.append("[[registry]]")
        out.append(f'id = "{entry["id"]}"')
        out.append(f'name = "{entry["name"]}"')
        for opt in ("status", "cite"):
            if opt in entry:
                out.append(f'{opt} = "{entry[opt]}"')
        out.append("[registry.entries]")
        for key, val in entry["entries"].items():
            if isinstance(val, list):
                out.append(f"{key} = [{_num(val[0])}, {_num(val[1])}]")
            else:
                out.append(f"{key} = {_num(val)}")
        out.append("")

    return "\n".join(out).rstrip("\n") + "\n"


def emit_header(doc: dict) -> str:
    out = [
        BANNER,
        "#pragma once",
        "",
        "namespace nukesim::constants {",
        "",
    ]

    for entry in doc.get("constant", []):
        cid, name = entry["id"], entry["name"]
        out.append(f"// {cid} — {entry['status']}; cite: {entry['cite']}")
        if entry["status"] == "PENDING":
            out.append(f"// PENDING, resolved_by {entry['resolved_by']}. 03 §1 requires that")
            out.append("// reading it fail; referencing this deleted function is a compile error.")
            out.append(f"double {name}() = delete;")
            out.append("")
            continue
        if entry.get("use") == "crosscheck":
            out.append("// use=crosscheck: MUST NOT enter tallies or gates (MAJ-11).")
        out.append(f"inline constexpr double {name} = {_num(entry['value'])};")
        if "lo" in entry:
            out.append(f"inline constexpr double {name}_lo = {_num(entry['lo'])};")
            out.append(f"inline constexpr double {name}_hi = {_num(entry['hi'])};")
            # 03 §1 requires a unit test asserting lo <= value <= hi. Generating
            # it as a static_assert is strictly stronger: it cannot be forgotten
            # for a new constant, and it fails at compile time rather than at
            # ctest time.
            out.append(
                f"static_assert({name}_lo <= {name} && {name} <= {name}_hi,"
                f' "{cid}: value outside its declared band");'
            )
        out.append("")

    for entry in doc.get("band", []):
        out.append(f"// {entry['id']} — {entry['status']}; cite: {entry['cite']}")
        out.append("// Band only: a gate band has no nominal (ADR-015).")
        out.append(f"inline constexpr double {entry['name']}_lo = {_num(entry['lo'])};")
        out.append(f"inline constexpr double {entry['name']}_hi = {_num(entry['hi'])};")
        out.append(
            f"static_assert({entry['name']}_lo < {entry['name']}_hi,"
            f' "{entry["id"]}: band requires lo < hi");'
        )
        out.append("")

    for entry in doc.get("registry", []):
        out.append(f"// {entry['id']} — {entry['status']}; cite: {entry['cite']}")
        out.append(f"namespace {entry['name']} {{")
        for key, val in entry["entries"].items():
            if isinstance(val, list):
                out.append(f"inline constexpr double {key}_lo = {_num(val[0])};")
                out.append(f"inline constexpr double {key}_hi = {_num(val[1])};")
            elif isinstance(val, int) and not isinstance(val, bool):
                out.append(f"inline constexpr int {key} = {val};")
            else:
                out.append(f"inline constexpr double {key} = {_num(val)};")
        out.append(f"}}  // namespace {entry['name']}")
        out.append("")

    out.append("}  // namespace nukesim::constants")
    return "\n".join(out) + "\n"


def emit_cuh() -> str:
    # Every emitted value is constexpr, which nvcc accepts in both host and
    # device code, so the .cuh is a thin alias rather than a second copy.
    return (
        BANNER
        + "#pragma once\n"
        + "\n"
        + "// Device-side view. constexpr is usable from __device__ code, so there is\n"
        + "// deliberately no duplicated table here — one definition, one source.\n"
        + '#include "constants_generated.h"\n'
    )


# --------------------------------------------------------------------------

OUTPUTS = {
    "data/constants.toml": emit_runtime_toml,
    "src/core/constants/constants_generated.h": emit_header,
    "src/core/constants/constants_generated.cuh": lambda _doc: emit_cuh(),
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if any generated output differs from what would be written")
    args = parser.parse_args()

    try:
        with STRICT.open("rb") as handle:
            doc = tomllib.load(handle)
        validate(doc)
        derived = resolve_derived(doc)
    except GenError as exc:
        print(f"gen_constants: ERROR: {exc}", file=sys.stderr)
        return 1
    except tomllib.TOMLDecodeError as exc:
        print(f"gen_constants: ERROR: {STRICT} is not valid TOML: {exc}", file=sys.stderr)
        return 1

    stale = []
    for rel, render in OUTPUTS.items():
        path = ROOT / rel
        text = render(doc)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.check:
            if current != text:
                stale.append(rel)
        elif current != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"gen_constants: wrote {rel}")

    if args.check and stale:
        print("gen_constants: STALE (regenerate and commit): " + ", ".join(stale), file=sys.stderr)
        return 1

    n = sum(len(doc.get(k, [])) for k in ("constant", "band", "registry"))
    for cid, val in derived.items():
        print(f"gen_constants: derived {cid} = {val:.7e}")
    print(f"gen_constants: OK ({n} entries{', all outputs current' if args.check else ''})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
