// GENERATED by tools/gen_constants — DO NOT EDIT.
// Source of truth: spec/appendix/constants.data.toml (03 §1, 01 §8).
// Regenerate with: python tools/gen_constants/gen_constants.py
#pragma once

// Device-side view. constexpr is usable from __device__ code, so there is
// deliberately no duplicated table here — one definition, one source.
#include "constants.h"
