// GENERATED by tools/gen_constants — DO NOT EDIT.
// Source of truth: spec/appendix/constants.data.toml (03 §1, 01 §8).
// Regenerate with: python tools/gen_constants/gen_constants.py

#pragma once

#include <stdexcept>
#include <string>
#include <string_view>

namespace ns::consts {

// C-010 — PUBLIC; cite: ENDF, Primer
inline constexpr double sigma_f_pu239_fast = 1.8;
inline constexpr double sigma_f_pu239_fast_lo = 1.7;
inline constexpr double sigma_f_pu239_fast_hi = 1.8;
static_assert(sigma_f_pu239_fast_lo <= sigma_f_pu239_fast && sigma_f_pu239_fast <= sigma_f_pu239_fast_hi, "C-010: value outside its declared band");

// C-011 — PUBLIC; cite: ENDF
inline constexpr double sigma_f_u235_fast = 1.2;

// C-012 — PUBLIC; cite: ENDF
inline constexpr double sigma_f_u238_fast = 0.5;

// C-020 — PUBLIC; cite: NWFAQ-8
inline constexpr double nu_bar_pu239_total = 2.9;

// C-021 — PUBLIC; cite: NWFAQ-8
inline constexpr double nu_bar_u235_total = 2.4;

// C-021b — PUBLIC; cite: ENDF
inline constexpr double nu_bar_u238_total = 2.8;
inline constexpr double nu_bar_u238_total_lo = 2.5;
inline constexpr double nu_bar_u238_total_hi = 2.9;
static_assert(nu_bar_u238_total_lo <= nu_bar_u238_total && nu_bar_u238_total <= nu_bar_u238_total_hi, "C-021b: value outside its declared band");

// C-022 — PUBLIC; cite: keepin, ENDF
inline constexpr double beta_pu239 = 0.002;

// C-022b — PUBLIC; cite: keepin, ENDF
inline constexpr double beta_u235 = 0.0065;

// C-022c — PUBLIC; cite: keepin, ENDF
inline constexpr double beta_u238 = 0.0148;

// C-022d — PUBLIC; cite: keepin, ENDF
inline constexpr double beta_pu240 = 0.0026;

// C-022e — PUBLIC; cite: keepin, ENDF
inline constexpr double beta_pu241 = 0.0049;

// C-030 — DECLASSIFIED; cite: Primer, NWFAQ
inline constexpr double generation_time_uncompressed = 10.0;

// C-031 — PUBLIC; cite: Primer
inline constexpr double neutron_speed_1mev = 1400000000.0;

// C-032 — DECLASSIFIED; cite: Primer
inline constexpr double fission_mfp_pu_normal_density = 12.7;

// C-040 — PUBLIC; cite: Primer
inline constexpr double e_f_prompt_deposited = 180.0;

// C-041 — PUBLIC; cite: derived
inline constexpr double phi_kt_fissions_per_kiloton = 1.4508041093079906e+23;

// C-051 — DECLASSIFIED; cite: NWFAQ-8.1.1
inline constexpr double urchin_initiator_output = 150000000.0;
inline constexpr double urchin_initiator_output_lo = 100000000.0;
inline constexpr double urchin_initiator_output_hi = 200000000.0;
static_assert(urchin_initiator_output_lo <= urchin_initiator_output && urchin_initiator_output <= urchin_initiator_output_hi, "C-051: value outside its declared band");

// C-052 — DECLASSIFIED; cite: NWFAQ-8.1.1
inline constexpr double pit_criticality_fraction_uncompressed_tamped = 0.78;
inline constexpr double pit_criticality_fraction_uncompressed_tamped_lo = 0.68;
inline constexpr double pit_criticality_fraction_uncompressed_tamped_hi = 0.88;
static_assert(pit_criticality_fraction_uncompressed_tamped_lo <= pit_criticality_fraction_uncompressed_tamped && pit_criticality_fraction_uncompressed_tamped <= pit_criticality_fraction_uncompressed_tamped_hi, "C-052: value outside its declared band");

// C-053 — DECLASSIFIED; cite: NWFAQ-2 prose ("3–4"), reconciled via ρ⁻² scaling from C-052
inline constexpr double critical_masses_at_2x_compression = 3.12;
inline constexpr double critical_masses_at_2x_compression_lo = 2.6;
inline constexpr double critical_masses_at_2x_compression_hi = 4.4;
static_assert(critical_masses_at_2x_compression_lo <= critical_masses_at_2x_compression && critical_masses_at_2x_compression <= critical_masses_at_2x_compression_hi, "C-053: value outside its declared band");

// C-060 — DECLASSIFIED; cite: Wellerstein-2015, NWFAQ
inline constexpr double compression_ratio = 2.2;
inline constexpr double compression_ratio_lo = 2.0;
inline constexpr double compression_ratio_hi = 2.5;
static_assert(compression_ratio_lo <= compression_ratio && compression_ratio <= compression_ratio_hi, "C-060: value outside its declared band");

// C-061 — PUBLIC; cite: NWFAQ-8.1.1
inline constexpr double comp_b_detonation_velocity = 7.9;

// C-062 — PUBLIC; cite: NWFAQ-8.1.1
inline constexpr double baratol_detonation_velocity = 4.9;

// C-070 — PUBLIC; cite: Guderley-1942, Lazarus-1981
inline constexpr double guderley_alpha_spherical_gamma_5_3 = 0.688377;

// C-071 — DECLASSIFIED; cite: NWFAQ-8.1.1
inline constexpr double x_unit_detonation_simultaneity = 10.0;

// C-072 — DECLASSIFIED; cite: NWFAQ-8.1.1
inline constexpr double he_assembly_symmetry_tolerance = 5.0;

// C-100 — DECLASSIFIED; cite: NWFAQ-8.1.1
inline constexpr double od_urchin_initiator = 2.0;
inline constexpr double od_urchin_initiator_mass_kg = 0.007;

// C-101 — RECONSTRUCTED; cite: CM
inline constexpr double od_initiator_cavity = 2.1;

// C-102 — DECLASSIFIED; cite: LA-3067
inline constexpr double od_pu_ga_core = 9.17;
inline constexpr double od_pu_ga_core_mass_kg = 6.15;

// C-103 — RECONSTRUCTED; cite: CM, NWFAQ-8.1.1
inline constexpr double od_natural_u_tamper = 22.86;
inline constexpr double od_natural_u_tamper_mass_lo_kg = 108.0;
inline constexpr double od_natural_u_tamper_mass_hi_kg = 111.0;

// C-104 — DECLASSIFIED; cite: NWFAQ-8.1.1
inline constexpr double od_b10_acrylic_shell = 23.5;

// C-105 — RECONSTRUCTED; cite: CM
inline constexpr double od_aluminum_pusher = 46.99;
inline constexpr double od_aluminum_pusher_mass_lo_kg = 128.0;
inline constexpr double od_aluminum_pusher_mass_hi_kg = 130.0;

// C-106 — RECONSTRUCTED; cite: CM
inline constexpr double od_inner_he_booster = 92.075;
inline constexpr double od_inner_he_booster_mass_kg = 608.0;

// C-107 — DECLASSIFIED; cite: NWFAQ-8.1.1
inline constexpr double od_lens_he_layer = 137.8;
inline constexpr double od_lens_he_layer_mass_lo_kg = 1800.0;
inline constexpr double od_lens_he_layer_mass_hi_kg = 1900.0;

// C-108 — RECONSTRUCTED; cite: CM
inline constexpr double od_cork_liner = 140.3;

// C-109 — RECONSTRUCTED; cite: CM
inline constexpr double od_duralumin_case = 145.4;

// C-910 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_pu239 = 239.0522;

// C-911 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_pu240 = 240.0538;

// C-912 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_u235 = 235.0439;

// C-913 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_u238 = 238.0508;

// C-914 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_u234 = 234.041;

// C-915a — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_ga69 = 68.9256;

// C-915b — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_ga71 = 70.9247;

// C-916 — PUBLIC; cite: SI (exact)
inline constexpr double avogadro_constant = 6.02214076e+23;

// C-917 — PUBLIC; cite: SI (exact)
inline constexpr double mev_to_joule = 1.602176634e-13;

// C-918 — PUBLIC; cite: convention (exact)
inline constexpr double kiloton_tnt_to_joule = 4184000000000.0;

// C-919 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_pu241 = 241.0568;

// C-920 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_b10 = 10.0129;

// C-921 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_b11 = 11.0093;

// C-922 — PUBLIC; cite: SI (definitional)
inline constexpr double molar_mass_c12 = 12.0;

// C-923 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_h1 = 1.00783;

// C-924 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_o16 = 15.9949;

// C-925 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_n14 = 14.0031;

// C-926 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_al27 = 26.9815;

// C-927 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_be9 = 9.01218;

// C-928 — PUBLIC; cite: NNDC/AME2020
inline constexpr double molar_mass_po210 = 209.9829;

// C-929 — PUBLIC; cite: IUPAC
inline constexpr double molar_mass_w_natural = 183.84;

// C-903 — SIM; cite: 02 §3 main loop (integer counters only, MAJ-21)
inline constexpr double alpha_mode_eigen_refresh_interval = 10;

// C-904 — SIM; cite: 01 §4 log-renorm
inline constexpr double population_renormalization_ceiling = 1e+30;

// C-905 — PENDING; cite: 09 §1 temperature calibration
// PENDING, resolved_by M7-T2. 03 §1 requires that
// reading it fail; referencing this deleted function is a compile error.
double render_scales() = delete;

// C-906 — PENDING; cite: 01 §5 (C-071/C-072 rule)
// PENDING, resolved_by M6-T3. 03 §1 requires that
// reading it fail; referencing this deleted function is a compile error.
double asymmetry_coefficient_c_a() = delete;

// C-909 — SIM; cite: 01 §6 E6 (F_n < eps*F_peak, BLK-03)
inline constexpr double quench_epsilon = 0.0001;

// C-909b — SIM; cite: 02 §3 hydro_moved_significantly
inline constexpr double eigen_refresh_dr_frac = 0.005;

// C-930 — SIM; cite: gate design choice, SIM; + benchmark_uncertainty (08 §1 rule)
inline constexpr double g0_k_deviation_tolerance = 500.0;

// C-931 — SIM; cite: gate design choice, SIM (batch sized to reach it, C-900)
inline constexpr double g0_sigma_ceiling = 25.0;

// C-932 — SIM; cite: SIM
inline constexpr double g0c_absolute_equivalence_bound = 100.0;

// C-945 — PENDING; cite: SIM (dev hardware-derived, ADR-009)
// PENDING, resolved_by M4-T4. 03 §1 requires that
// reading it fail; referencing this deleted function is a compile error.
double g4_perf_budgets() = delete;

// C-933 — SIM; cite: C-052 ± 0.10 (prose-source width), SIM
// Band only: a gate band has no nominal (ADR-015).
inline constexpr double g1a_mass_fraction_band_lo = 0.68;
inline constexpr double g1a_mass_fraction_band_hi = 0.88;
static_assert(g1a_mass_fraction_band_lo < g1a_mass_fraction_band_hi, "C-933: band requires lo < hi");

// C-934 — SIM; cite: one-group image of C-933; derivation recorded in gates.toml notes; SIM
// Band only: a gate band has no nominal (ADR-015).
inline constexpr double g1a_derived_k_band_lo = 0.84;
inline constexpr double g1a_derived_k_band_hi = 0.96;
static_assert(g1a_derived_k_band_lo < g1a_derived_k_band_hi, "C-934: band requires lo < hi");

// C-935 — SIM; cite: C-053 ±40% (prose source), SIM
// Band only: a gate band has no nominal (ADR-015).
inline constexpr double g1b_critical_masses_at_2rho0_lo = 2.6;
inline constexpr double g1b_critical_masses_at_2rho0_hi = 4.4;
static_assert(g1b_critical_masses_at_2rho0_lo < g1b_critical_masses_at_2rho0_hi, "C-935: band requires lo < hi");

// C-936 — SIM; cite: one-group image of C-935; SIM
// Band only: a gate band has no nominal (ADR-015).
inline constexpr double g1b_k_at_2x_band_lo = 1.35;
inline constexpr double g1b_k_at_2x_band_hi = 1.85;
static_assert(g1b_k_at_2x_band_lo < g1b_k_at_2x_band_hi, "C-936: band requires lo < hi");

// C-937 — SIM; cite: k(2.0)/k(1.0); SIM
// Band only: a gate band has no nominal (ADR-015).
inline constexpr double g1b_k_ratio_band_lo = 1.5;
inline constexpr double g1b_k_ratio_band_hi = 2.0;
static_assert(g1b_k_ratio_band_lo < g1b_k_ratio_band_hi, "C-937: band requires lo < hi");

// C-940 — PUBLIC; cite: envelope of C-091/092/093 incl. Selby ±2
// Band only: a gate band has no nominal (ADR-015).
inline constexpr double g2_yield_band_lo = 16.6;
inline constexpr double g2_yield_band_hi = 26.8;
static_assert(g2_yield_band_lo < g2_yield_band_hi, "C-940: band requires lo < hi");

// C-941 — SIM; cite: C-090 (0.15–0.17) widened ±3 pp for few-group + Tier-2 error; SIM
// Band only: a gate band has no nominal (ADR-015).
inline constexpr double g2_pu_burnup_band_lo = 0.12;
inline constexpr double g2_pu_burnup_band_hi = 0.2;
static_assert(g2_pu_burnup_band_lo < g2_pu_burnup_band_hi, "C-941: band requires lo < hi");

// C-942 — SIM; cite: C-094 ±10 pp; SIM
// Band only: a gate band has no nominal (ADR-015).
inline constexpr double g2_tamper_yield_band_lo = 0.1;
inline constexpr double g2_tamper_yield_band_hi = 0.3;
static_assert(g2_tamper_yield_band_lo < g2_tamper_yield_band_hi, "C-942: band requires lo < hi");

// C-900 — SIM; cite: 08 §2 gate procedure (QC-06)
namespace eigen_gate_config {
inline constexpr double batch = 1000000.0;
inline constexpr int inactive = 50;
inline constexpr int active = 200;
}  // namespace eigen_gate_config

// C-900b — SIM; cite: 08 §2 (QC-06)
namespace eigen_interactive_config {
inline constexpr double batch = 100000.0;
inline constexpr int inactive = 10;
inline constexpr int active = 30;
}  // namespace eigen_interactive_config

// C-900c — SIM; cite: 08 §2
namespace eigen_cpu_ref_smoke_config {
inline constexpr double batch = 100000.0;
inline constexpr int inactive = 10;
inline constexpr int active = 50;
}  // namespace eigen_cpu_ref_smoke_config

// C-901 — SIM; cite: 05 §2
namespace eigen_tolerances {
inline constexpr double entropy_window = 0.001;
inline constexpr double k = 0.0001;
}  // namespace eigen_tolerances

// C-902 — SIM; cite: 05 §1
namespace weight_cutoffs {
inline constexpr double w_min = 0.0001;
inline constexpr double w_surv = 0.01;
}  // namespace weight_cutoffs

// C-907 — SIM; cite: 04 §2 Philox stream layout
namespace rng_stream_registry {
inline constexpr int source = 1;
inline constexpr int flight = 2;
inline constexpr int collision = 3;
inline constexpr int fission = 4;
inline constexpr int scatter = 5;
inline constexpr int hydro = 6;
inline constexpr int render = 7;
}  // namespace rng_stream_registry

// C-908 — SIM; cite: 01 §E2b (fixed Cartesian mesh; degeneracy on a 1-cell mesh, QC)
namespace eigen_entropy_mesh {
inline constexpr int nx = 8;
inline constexpr int ny = 8;
inline constexpr int nz = 8;
}  // namespace eigen_entropy_mesh

// C-943 — SIM; cite: ±(2–3)× around ~57 e-foldings at α≈1e8 (research doc §3); SIM
namespace g2_timing_bands {
inline constexpr double fwhm_ns_lo = 5.0;
inline constexpr double fwhm_ns_hi = 100.0;
inline constexpr double t_fire_to_peak_s_lo = 1e-07;
inline constexpr double t_fire_to_peak_s_hi = 1.5e-06;
inline constexpr double peak_alpha_per_s_lo = 20000000.0;
inline constexpr double peak_alpha_per_s_hi = 300000000.0;
}  // namespace g2_timing_bands

// C-944 — SIM; cite: (b) visible-degradation requirement; (c) published-tolerance claim (C-071/C-072), NOT calibrated; SIM
namespace g3_degradation_criteria {
inline constexpr double degraded_500ns_max_ratio = 0.9;
inline constexpr double tolerated_10ns_min_ratio = 0.97;
}  // namespace g3_degradation_criteria

// C-946 — SIM; cite: R-13; SIM
namespace q_validity_thresholds {
inline constexpr double warn = 0.02;
inline constexpr double conditional = 0.05;
}  // namespace q_validity_thresholds

// ---------------------------------------------------------------------
// use = crosscheck (04 §1). Readouts and comparisons ONLY.
// A compute-path source referencing ns::consts::crosscheck:: is a defect,
// and 11 §4's static check greps for exactly that qualifier (01 §8.3).
// ---------------------------------------------------------------------
namespace crosscheck {

// C-013 — PUBLIC; cite: ENDF
inline constexpr double sigma_f_pu239_thermal = 750.0;

// C-033 — DECLASSIFIED; cite: Primer
inline constexpr double scattering_mfp = 2.5;

// C-042 — PUBLIC; cite: NP-1771
inline constexpr double kt_per_kg_pu239_sherbeck = 18.29;

// C-043 — PUBLIC; cite: NP-1771
inline constexpr double kt_per_kg_u235_sherbeck = 17.74;

// C-050 — DECLASSIFIED; cite: Wellerstein-2015
inline constexpr double critical_mass_bare_pu239_alpha = 10.0;

// C-050b — PUBLIC; cite: Jezebel PMF-001
inline constexpr double critical_mass_bare_pu_delta = 16.5;
inline constexpr double critical_mass_bare_pu_delta_lo = 16.0;
inline constexpr double critical_mass_bare_pu_delta_hi = 17.0;
static_assert(critical_mass_bare_pu_delta_lo <= critical_mass_bare_pu_delta && critical_mass_bare_pu_delta <= critical_mass_bare_pu_delta_hi, "C-050b: value outside its declared band");

// C-090 — PUBLIC; cite: Wellerstein-2013
inline constexpr double trinity_pu_burnup = 0.16;
inline constexpr double trinity_pu_burnup_lo = 0.15;
inline constexpr double trinity_pu_burnup_hi = 0.17;
static_assert(trinity_pu_burnup_lo <= trinity_pu_burnup && trinity_pu_burnup <= trinity_pu_burnup_hi, "C-090: value outside its declared band");

// C-091 — PUBLIC; cite: Selby-2021
inline constexpr double trinity_yield_radiochemistry_1945 = 18.6;

// C-092 — PUBLIC; cite: DOE
inline constexpr double trinity_yield_doe_official = 21.0;

// C-093 — PUBLIC; cite: Selby-2021
inline constexpr double trinity_yield_selby_2021 = 24.8;
inline constexpr double trinity_yield_selby_2021_lo = 22.8;
inline constexpr double trinity_yield_selby_2021_hi = 26.8;
static_assert(trinity_yield_selby_2021_lo <= trinity_yield_selby_2021 && trinity_yield_selby_2021 <= trinity_yield_selby_2021_hi, "C-093: value outside its declared band");

// C-094 — DECLASSIFIED; cite: NWFAQ-8.1.1
inline constexpr double u238_tamper_yield_share = 0.2;
inline constexpr double u238_tamper_yield_share_lo = 0.1;
inline constexpr double u238_tamper_yield_share_hi = 0.3;
static_assert(u238_tamper_yield_share_lo <= u238_tamper_yield_share && u238_tamper_yield_share <= u238_tamper_yield_share_hi, "C-094: value outside its declared band");

// C-915 — PUBLIC; cite: IUPAC
inline constexpr double molar_mass_ga_natural = 69.723;

}  // namespace crosscheck

// Runtime lookup by constant id (04 §1). Tests and diagnostics use this;
// hot paths use the constexpr names above.
inline double get(std::string_view id) {
    if (id == "C-010") return sigma_f_pu239_fast;
    if (id == "C-011") return sigma_f_u235_fast;
    if (id == "C-012") return sigma_f_u238_fast;
    if (id == "C-013") return crosscheck::sigma_f_pu239_thermal;
    if (id == "C-020") return nu_bar_pu239_total;
    if (id == "C-021") return nu_bar_u235_total;
    if (id == "C-021b") return nu_bar_u238_total;
    if (id == "C-022") return beta_pu239;
    if (id == "C-022b") return beta_u235;
    if (id == "C-022c") return beta_u238;
    if (id == "C-022d") return beta_pu240;
    if (id == "C-022e") return beta_pu241;
    if (id == "C-030") return generation_time_uncompressed;
    if (id == "C-031") return neutron_speed_1mev;
    if (id == "C-032") return fission_mfp_pu_normal_density;
    if (id == "C-033") return crosscheck::scattering_mfp;
    if (id == "C-040") return e_f_prompt_deposited;
    if (id == "C-041") return phi_kt_fissions_per_kiloton;
    if (id == "C-042") return crosscheck::kt_per_kg_pu239_sherbeck;
    if (id == "C-043") return crosscheck::kt_per_kg_u235_sherbeck;
    if (id == "C-050") return crosscheck::critical_mass_bare_pu239_alpha;
    if (id == "C-050b") return crosscheck::critical_mass_bare_pu_delta;
    if (id == "C-051") return urchin_initiator_output;
    if (id == "C-052") return pit_criticality_fraction_uncompressed_tamped;
    if (id == "C-053") return critical_masses_at_2x_compression;
    if (id == "C-060") return compression_ratio;
    if (id == "C-061") return comp_b_detonation_velocity;
    if (id == "C-062") return baratol_detonation_velocity;
    if (id == "C-070") return guderley_alpha_spherical_gamma_5_3;
    if (id == "C-071") return x_unit_detonation_simultaneity;
    if (id == "C-072") return he_assembly_symmetry_tolerance;
    if (id == "C-090") return crosscheck::trinity_pu_burnup;
    if (id == "C-091") return crosscheck::trinity_yield_radiochemistry_1945;
    if (id == "C-092") return crosscheck::trinity_yield_doe_official;
    if (id == "C-093") return crosscheck::trinity_yield_selby_2021;
    if (id == "C-094") return crosscheck::u238_tamper_yield_share;
    if (id == "C-100") return od_urchin_initiator;
    if (id == "C-101") return od_initiator_cavity;
    if (id == "C-102") return od_pu_ga_core;
    if (id == "C-103") return od_natural_u_tamper;
    if (id == "C-104") return od_b10_acrylic_shell;
    if (id == "C-105") return od_aluminum_pusher;
    if (id == "C-106") return od_inner_he_booster;
    if (id == "C-107") return od_lens_he_layer;
    if (id == "C-108") return od_cork_liner;
    if (id == "C-109") return od_duralumin_case;
    if (id == "C-910") return molar_mass_pu239;
    if (id == "C-911") return molar_mass_pu240;
    if (id == "C-912") return molar_mass_u235;
    if (id == "C-913") return molar_mass_u238;
    if (id == "C-914") return molar_mass_u234;
    if (id == "C-915") return crosscheck::molar_mass_ga_natural;
    if (id == "C-915a") return molar_mass_ga69;
    if (id == "C-915b") return molar_mass_ga71;
    if (id == "C-916") return avogadro_constant;
    if (id == "C-917") return mev_to_joule;
    if (id == "C-918") return kiloton_tnt_to_joule;
    if (id == "C-919") return molar_mass_pu241;
    if (id == "C-920") return molar_mass_b10;
    if (id == "C-921") return molar_mass_b11;
    if (id == "C-922") return molar_mass_c12;
    if (id == "C-923") return molar_mass_h1;
    if (id == "C-924") return molar_mass_o16;
    if (id == "C-925") return molar_mass_n14;
    if (id == "C-926") return molar_mass_al27;
    if (id == "C-927") return molar_mass_be9;
    if (id == "C-928") return molar_mass_po210;
    if (id == "C-929") return molar_mass_w_natural;
    if (id == "C-903") return alpha_mode_eigen_refresh_interval;
    if (id == "C-904") return population_renormalization_ceiling;
    if (id == "C-905") throw std::runtime_error("C-905 is PENDING (resolved_by M7-T2) and must not be read");
    if (id == "C-906") throw std::runtime_error("C-906 is PENDING (resolved_by M6-T3) and must not be read");
    if (id == "C-909") return quench_epsilon;
    if (id == "C-909b") return eigen_refresh_dr_frac;
    if (id == "C-930") return g0_k_deviation_tolerance;
    if (id == "C-931") return g0_sigma_ceiling;
    if (id == "C-932") return g0c_absolute_equivalence_bound;
    if (id == "C-945") throw std::runtime_error("C-945 is PENDING (resolved_by M4-T4) and must not be read");
    if (id == "C-933") throw std::runtime_error("C-933 is a band with no nominal (ADR-015); use get_lo/get_hi");
    if (id == "C-934") throw std::runtime_error("C-934 is a band with no nominal (ADR-015); use get_lo/get_hi");
    if (id == "C-935") throw std::runtime_error("C-935 is a band with no nominal (ADR-015); use get_lo/get_hi");
    if (id == "C-936") throw std::runtime_error("C-936 is a band with no nominal (ADR-015); use get_lo/get_hi");
    if (id == "C-937") throw std::runtime_error("C-937 is a band with no nominal (ADR-015); use get_lo/get_hi");
    if (id == "C-940") throw std::runtime_error("C-940 is a band with no nominal (ADR-015); use get_lo/get_hi");
    if (id == "C-941") throw std::runtime_error("C-941 is a band with no nominal (ADR-015); use get_lo/get_hi");
    if (id == "C-942") throw std::runtime_error("C-942 is a band with no nominal (ADR-015); use get_lo/get_hi");
    throw std::runtime_error("unknown constant id: " + std::string(id));
}

// Molar mass by species name (appendix §3). Throws for an unknown species:
// a missing molar mass silently corrupts every macroscopic cross section,
// so it must never fall back to a default.
inline double molar_mass(std::string_view species) {
    if (species == "Pu239") return molar_mass_pu239;
    if (species == "Pu240") return molar_mass_pu240;
    if (species == "U235") return molar_mass_u235;
    if (species == "U238") return molar_mass_u238;
    if (species == "U234") return molar_mass_u234;
    if (species == "Ga") return crosscheck::molar_mass_ga_natural;
    if (species == "Ga69") return molar_mass_ga69;
    if (species == "Ga71") return molar_mass_ga71;
    if (species == "Pu241") return molar_mass_pu241;
    if (species == "B10") return molar_mass_b10;
    if (species == "B11") return molar_mass_b11;
    if (species == "C12") return molar_mass_c12;
    if (species == "H1") return molar_mass_h1;
    if (species == "O16") return molar_mass_o16;
    if (species == "N14") return molar_mass_n14;
    if (species == "Al27") return molar_mass_al27;
    if (species == "Be9") return molar_mass_be9;
    if (species == "Po210") return molar_mass_po210;
    if (species == "W") return molar_mass_w_natural;
    throw std::runtime_error("no molar mass for species: " + std::string(species) + " (appendix §3 completeness rule)");
}

/// True if the species has a molar mass, without throwing.
inline bool has_molar_mass(std::string_view species) {
    return species == "Pu239" || species == "Pu240" || species == "U235" || species == "U238" || species == "U234" || species == "Ga" || species == "Ga69" || species == "Ga71" || species == "Pu241" || species == "B10" || species == "B11" || species == "C12" || species == "H1" || species == "O16" || species == "N14" || species == "Al27" || species == "Be9" || species == "Po210" || species == "W";
}

inline double get_lo(std::string_view id) {
    if (id == "C-010") return sigma_f_pu239_fast_lo;
    if (id == "C-021b") return nu_bar_u238_total_lo;
    if (id == "C-050b") return crosscheck::critical_mass_bare_pu_delta_lo;
    if (id == "C-051") return urchin_initiator_output_lo;
    if (id == "C-052") return pit_criticality_fraction_uncompressed_tamped_lo;
    if (id == "C-053") return critical_masses_at_2x_compression_lo;
    if (id == "C-060") return compression_ratio_lo;
    if (id == "C-090") return crosscheck::trinity_pu_burnup_lo;
    if (id == "C-093") return crosscheck::trinity_yield_selby_2021_lo;
    if (id == "C-094") return crosscheck::u238_tamper_yield_share_lo;
    if (id == "C-933") return g1a_mass_fraction_band_lo;
    if (id == "C-934") return g1a_derived_k_band_lo;
    if (id == "C-935") return g1b_critical_masses_at_2rho0_lo;
    if (id == "C-936") return g1b_k_at_2x_band_lo;
    if (id == "C-937") return g1b_k_ratio_band_lo;
    if (id == "C-940") return g2_yield_band_lo;
    if (id == "C-941") return g2_pu_burnup_band_lo;
    if (id == "C-942") return g2_tamper_yield_band_lo;
    throw std::runtime_error("no lo bound for constant id: " + std::string(id));
}

inline double get_hi(std::string_view id) {
    if (id == "C-010") return sigma_f_pu239_fast_hi;
    if (id == "C-021b") return nu_bar_u238_total_hi;
    if (id == "C-050b") return crosscheck::critical_mass_bare_pu_delta_hi;
    if (id == "C-051") return urchin_initiator_output_hi;
    if (id == "C-052") return pit_criticality_fraction_uncompressed_tamped_hi;
    if (id == "C-053") return critical_masses_at_2x_compression_hi;
    if (id == "C-060") return compression_ratio_hi;
    if (id == "C-090") return crosscheck::trinity_pu_burnup_hi;
    if (id == "C-093") return crosscheck::trinity_yield_selby_2021_hi;
    if (id == "C-094") return crosscheck::u238_tamper_yield_share_hi;
    if (id == "C-933") return g1a_mass_fraction_band_hi;
    if (id == "C-934") return g1a_derived_k_band_hi;
    if (id == "C-935") return g1b_critical_masses_at_2rho0_hi;
    if (id == "C-936") return g1b_k_at_2x_band_hi;
    if (id == "C-937") return g1b_k_ratio_band_hi;
    if (id == "C-940") return g2_yield_band_hi;
    if (id == "C-941") return g2_pu_burnup_band_hi;
    if (id == "C-942") return g2_tamper_yield_band_hi;
    throw std::runtime_error("no hi bound for constant id: " + std::string(id));
}

}  // namespace ns::consts
