#!/usr/bin/env python3
"""Generate data/benchmarks/gates.toml (03 §10, M1-T5-a).

gates.toml is NEVER hand-edited (03 §10) -- run this. Gate STRUCTURE (which gates, their
scenarios, seed sets, eigen config, which criteria) comes from spec/08-validation.md §2 and
is encoded in GATES below; criterion THRESHOLDS are looked up from the constants
(data/constants.toml) by id, never inlined; and spec_sha256 = sha256 of 08-validation.md so
nukebench fails if the normative spec changed without regeneration + review (README §6).

Line endings are normalized (CRLF->LF) before hashing so spec_sha256 is identical on Windows
(dev) and Linux (CI) regardless of the git checkout EOL -- the C++ loader normalizes the same.

    python gen_gates.py            # write data/benchmarks/gates.toml
    python gen_gates.py --check    # exit 1 if the committed gates.toml is stale
"""
import argparse
import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SPEC_08 = REPO / "spec" / "08-validation.md"
OUT = REPO / "data" / "benchmarks" / "gates.toml"

# 08 §2 G0a/G0b: C-900 eigen; pass iff EVERY normative seed [1..5] has |k-1| <= 500 pcm +
# benchmark_uncertainty (C-930) AND sigma <= 25 pcm (C-931).
# G0c (differential, M1-T5-c-3): the ref eigen vs the gpu eigen on the SAME Godiva assembly must
# agree -- |k_ref - k_gpu| <= C-932 (100 pcm) AND <= 3*sqrt(sig_ref^2+sig_gpu^2) (08 §2 criterion a),
# on the fixed 3-seed set. `nukebench diff` runs both backends and compares; the k_equivalence_pcm
# criterion records the C-932 threshold. (Criteria (b) per-shell + (c) population-series follow when
# the GPU eigen exposes those series; G1-G5 need later milestones. Adding gates here is a data edit.)
_C900 = {"batch": 1000000, "inactive": 50, "active": 200}
_BARE_CRITERIA = [
    {"name": "k_deviation_pcm", "op": "abs_le", "constant_id": "C-930"},
    {"name": "sigma_pcm", "op": "le", "constant_id": "C-931"},
]
_DIFF_CRITERIA = [
    {"name": "k_equivalence_pcm", "op": "abs_le", "constant_id": "C-932"},
]
GATES = [
    {"id": "G0a", "title": "Godiva bare-sphere k_eff", "scenario": "data/scenarios/godiva.toml",
     "seeds": [1, 2, 3, 4, 5], "eigen": _C900, "criteria": _BARE_CRITERIA},
    {"id": "G0b", "title": "Jezebel bare-sphere k_eff", "scenario": "data/scenarios/jezebel.toml",
     "seeds": [1, 2, 3, 4, 5], "eigen": _C900, "criteria": _BARE_CRITERIA},
    {"id": "G0c", "title": "Godiva ref-vs-gpu k equivalence (cross-backend differential)",
     "scenario": "data/scenarios/godiva.toml", "seeds": [1, 2, 3], "eigen": _C900,
     "criteria": _DIFF_CRITERIA},
]


def _norm(raw: bytes) -> bytes:
    return raw.replace(b"\r\n", b"\n")


def spec_sha256() -> str:
    return hashlib.sha256(_norm(SPEC_08.read_bytes())).hexdigest()


def constant_values(ids) -> dict:
    """{id: value} for the requested constant ids, by a line scan of the STRICT source
    spec/appendix/constants.data.toml (the file gen_constants reads). A line scan, not a
    full TOML parse, so a malformed cite string elsewhere in the file cannot break it."""
    src = (REPO / "spec" / "appendix" / "constants.data.toml").read_text(encoding="utf-8")
    want, out, cur = set(ids), {}, None
    for line in src.splitlines():
        s = line.strip()
        m = re.match(r'id\s*=\s*"([^"]+)"', s)
        if m:
            cur = m.group(1)
            continue
        if cur in want:
            mv = re.match(r"value\s*=\s*([0-9.eE+-]+)\s*$", s)
            if mv:
                out[cur] = float(mv.group(1))
                cur = None
    missing = want - set(out)
    if missing:
        raise SystemExit(f"gen_gates: no value found for constants {sorted(missing)}")
    return out


def _num(v) -> str:
    return str(int(v)) if float(v) == int(v) else repr(float(v))


def render() -> bytes:
    vals = constant_values({c["constant_id"] for g in GATES for c in g["criteria"]})
    lines = [
        "# GENERATED by tools/gen_gates/gen_gates.py from spec/08-validation.md + the gate",
        "# threshold constants (spec/appendix/constants.data.toml). NEVER hand-edit -- run gen_gates.",
        "# nukebench fails if spec_sha256 != sha256(spec/08-validation.md) (03 section 10).",
        "schema_version = 1",
        'generated_from = "spec/08-validation.md"',
        f'spec_sha256    = "{spec_sha256()}"',
        "",
    ]
    for g in GATES:
        lines += [
            "[[gate]]",
            f'id = "{g["id"]}"',
            f'title = "{g["title"]}"',
            f'scenario = "{g["scenario"]}"',
            "seeds = [" + ", ".join(str(s) for s in g["seeds"]) + "]",
            "[gate.eigen]",
            f'batch = {g["eigen"]["batch"]}',
            f'inactive = {g["eigen"]["inactive"]}',
            f'active = {g["eigen"]["active"]}',
        ]
        for c in g["criteria"]:
            lines += [
                "[[gate.criterion]]",
                f'name = "{c["name"]}"',
                f'op = "{c["op"]}"',
                f'value = {_num(vals[c["constant_id"]])}',
                f'constant_id = "{c["constant_id"]}"',
            ]
        lines.append("")
    return ("\n".join(lines) + "\n").encode("utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed gates.toml is stale")
    args = ap.parse_args()
    content = render()
    if args.check:
        current = OUT.read_bytes() if OUT.exists() else b""
        if _norm(current) != content:
            print("gates.toml is STALE -- re-run tools/gen_gates/gen_gates.py", file=sys.stderr)
            sys.exit(1)
        print("gates.toml is up to date")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(content)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
