// GENERATED by tools/verify/rng_kat_gen.py — DO NOT EDIT.
//
// Project-local known-answer vector (04 §2). FROZEN: changing any value here
// changes every random number the project produces and requires an ADR.
//
// Produced by an independent Python Philox that first reproduces the three
// published Random123 vectors, so this file is external evidence about the
// wrapper layout (counter packing, sub-word order, float conversion) rather
// than a recording of what the C++ already did.

// First 16 uniform_f() of Stream(seed=0, stream=0).
inline constexpr float kRngKatUniformF[16] = {
    0.399046421f, 0.880520165f, 0.735712767f, 0.605481803f,
    0.972241163f, 0.362091064f, 0.693930864f, 0.0370940566f,
    0.0194494128f, 0.319445729f, 0.140946567f, 0.271746933f,
    0.787367761f, 0.415107012f, 0.604630649f, 0.426776767f,
};

// fork(42, 1000, 3) — must be identical in ref/ and gpu/ (04 §2c).
inline constexpr unsigned long long kRngKatFork42_1000_3 = 12597386599640143736ull;
